@startuml
class BetterExperimentation 

class ReportGeneratorService

class GenerateScoreService

class PrepareExperimentService

class LoadTestDataService

class LoadModelsService

class ExperimentalPipelineService

class ABPipelineService

class ABTestRepository

interface IDataFileRepository

class PandasDataFileRepository

interface IModelRepository

class SklearnModelRepository

class TensorflowModelRepository

BetterExperimentation -- GenerateScoreService
BetterExperimentation -- PrepareExperimentService
BetterExperimentation -- LoadTestDataService
BetterExperimentation -- ExperimentalPipelineService
BetterExperimentation -- ReportGeneratorService

ExperimentalPipelineService -- ABPipelineService
ABPipelineService -- ABTestRepository

IDataFileRepository <|-- PandasDataFileRepository
LoadDataFileService --> IDataFileRepository

IModelRepository <|-- SklearnModelRepository
IModelRepository <|-- GeneralModelRepository

LoadAllModelsService -- LoadModelService
LoadModelService --> IModelRepository
@enduml