@startuml
class ExpML 

class ReportGeneratorService

class GenerateScoreService

class PrepareContextService

class LoadTestDataService

class LoadModelService

class ExperimentalPipelineService

class ABPipelineService

class ABTestRepository

interface IDataFileRepository

class PandasDataFileRepository

interface IModelRepository

class SklearnModelRepository

ExpML -- GenerateScoreService
ExpML -- PrepareContextService
ExpML -- LoadTestDataService
ExpML -- ExperimentalPipelineService
ExpML -- ReportGeneratorService

ExperimentalPipelineService -- ABPipelineService
ABPipelineService -- ABTestRepository

IDataFileRepository <|-- PandasDataFileRepository
LoadTestDataService --> IDataFileRepository

IModelRepository <|-- SklearnModelRepository
IModelRepository <|-- GeneralModelRepository

LoadModelService --> IModelRepository

LoadModelService *-- PrepareContextService
@enduml