@startuml
class ExpML 

interface IReportGeneratorService

class ReportGeneratorService

interface IGenerateScoreService

class GenerateScoreService

interface IPrepareContextService

class PrepareContextService

interface ILoadTestDataService

class LoadTestDataService

interface ILoadModelService

class LoadModelService

interface IExperimentalPipelineService

class ExperimentalPipelineService

interface IStatisticalPipelineService

class StatisticalPipelineService

interface IABTestRepository

class ABTestRepository

interface IDataFileRepository

class PandasDataFileRepository

interface IModelRepository

class SklearnModelRepository

IExperimentalPipelineService <|-- ExperimentalPipelineService
IStatisticalPipelineService <|-- StatisticalPipelineService
ILoadModelService <|-- LoadModelService
ILoadTestDataService <|-- LoadTestDataService
IReportGeneratorService <|-- ReportGeneratorService
IPrepareContextService <|-- PrepareContextService
IGenerateScoreService <|-- GenerateScoreService
IDataFileRepository <|-- PandasDataFileRepository
IABTestRepository <|-- ABTestRepository
IModelRepository <|-- SklearnModelRepository
IModelRepository <|-- GeneralModelRepository

LoadModelService --* IModelRepository
PrepareContextService --* ILoadModelService
LoadTestDataService --* IDataFileRepository
StatisticalPipelineService --* IABTestRepository
ExperimentalPipelineService --* IStatisticalPipelineService

ExpML -- IGenerateScoreService
ExpML -- IPrepareContextService
ExpML -- ILoadTestDataService
ExpML -- IExperimentalPipelineService
ExpML -- IReportGeneratorService

@enduml