@startuml
	start
    :validate input parameters and load artifacts;
    :apply split of test data using kfold;
	while (for each model trained)
	:apply predict to each data group;
    :calculate score comparing result and expected to each data group;
    :store score result in dictionary;
	endwhile
    :apply Shapiro-Wilk Test;
    :apply Levene Test;

    if ("only two models?") then (yes)
        if ("Normal and homoscedastic score data?") then (yes)
            : Student's t-test;
        else (no)
            :Mann-Whitney test;
        endif
    else (no)
        if ("Normal and homoscedastic score data?") then (yes)
            :ANOVA test;
            if ("Significant differences?") then (yes)
            :Tukey test;
            else (no)
            endif
        else (no)
            :Kruskal-Wallis test;
            if ("Significant differences?") then (yes)
            :Mann-Whitney test;
            else (no)
            endif
        endif
    endif
    :processing of statistical test results;
    :deciding the best model around the metric;
    :report generation;
	stop
@enduml